version: '1.0'
steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: 'https://github.com/titukhan2000/springbootkubernates'
    revision: main
    stage: clone
  sonarqube:
    type: "sonar-scanner-cli"
    stage: "push"
    arguments:
      SONAR_HOST_URL: 'https://sonarcloud.io/' # replace with your host url
      SONAR_LOGIN: "828ec9c817d4b6704b2d06c0ad55b86eb6308cac" # replace with your access token
      SONAR_PROJECT_BASE_DIR: '/codefresh/volume/springbootkubernates' #replace with your working directory
      SONAR_SCANNER_CLI_VERSION: "latest"
  build_my_app:
    title: springboot image
    type: build
    stage: build
    image_name: springbootnew
    working_directory: '${{clone}}'
    tag: master
    disable_push: true
    dockerfile: Dockerfile  
  push_to_my_registry:
    type: parallel
    stage: push
    steps:
      pushing_to_docker:
        type: push
        title: Pushing to a registry
        candidate: '${{build_my_app}}'
        tag: v1.0.6
        registry: CodeFreshRegistry
        image_name: devilsdocker/codefreshdemo
      pushing_to_jfrog_bintray:
        type: push
        title: Pushing to a jfrog bintray
        candidate: '${{build_my_app}}'
        tag: v1.0.6
        registry: JFrogBintray
        image_name: jfrogcodefreshpackdemo
      pushing_to_jfrog:
        type: push
        title: Pushing to a jfrog
        candidate: '${{build_my_app}}'
        tag: v1.0.6
        registry: JFrogRegistry
        image_name: codefreshjfrog/jfrogdocker
stages:
  - clone
  - sonar
  - build
  - push
