# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "sonar"
  - "copy_to_shared_volume"
  - "shared-volume"
  - "push"

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: 'https://github.com/titukhan2000/springbootkubernates'
    revision: main
    stage: clone     
  PrintFileList:
    title: 'Listing files'
    stage: clone
    image: alpine:latest
    commands:
     - echo "${{CF_BUILD_ID}}"
     - 'ls -l'
    when:
      condition:
        all:
         myCondition: clone.result == 'success'
  build:
    title: "Building Docker image"
    type: "build"
    image_name: "titukhan2000/springbootkubernates"
    working_directory: "${{clone}}"
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    dockerfile: "Dockerfile"
    disable_push: true
    stage: "build"
    when:
      condition:
       any:
         myCondition: clone.result == 'success'
         ifLengthisfour: length("${{CF_BRANCH}}")==3
  copy_to_shared_volume:
    title: "Copy file to shared volume"
    type: "freestyle" 
    image: alpine:3.9 
    working_directory: "${{clone}}"
    commands:
      - ls -l /codefresh/volume/
      - cp ./artifact.example /codefresh/volume/artifact.example
    stage: "shared-volume"
  list_shared_volume:
    title: "List shared volume files"
    type: "freestyle" 
    image: alpine:3.9 
    working_directory: "${{clone}}"
    commands:
      - pwd
      - ls -l /codefresh/volume
    stage: "shared-volume"
  sonarqube:
     title: "SonarQube validations"
     type: "freestyle"
     stage: "sonar"
     image: gradle:4.7.0-jdk8-alpine
     working_directory: "${{clone}}"
     commands:
        - ls -ltr
        - chmod 777 gradlew
        - ./gradlew clean build sonarqube --no-daemon
     when:
          branch:
            only:
            - master
  approve_existing_version_update:
    type: pending-approval
    stage: push
    title: "Are you sure you want to update already existing image version?"
    description: |
       "Used for reverting changes without raising the service version"
    when:
      branch:
        only: 
         - main
      steps:
       - name: copy_to_shared_volume
         on:
           - success
